apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-performance-to-ready-clusters
  namespace: performance-addon
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["spoke451"]}
