apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-performance
  namespace: performance-addon
  annotations:
    apps.open-cluster-management.io/github-path: config/
spec:
  channel: acm-gitops-github
  name: flexran-performance
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-performance-to-ready-clusters
      


