apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c25,c0
    openshift.io/sa.scc.supplemental-groups: 1000600000/10000
    openshift.io/sa.scc.uid-range: 1000600000/10000
  labels:
    env: prod
    name: testlabel
  resourceVersion: "323974"
spec:
  finalizers:
  - kubernetes
